//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "GripperEventServiceInHandler.hh"

#include <iostream>

GripperEventServiceInHandler::GripperEventServiceInHandler(Smart::InputSubject<Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult>> *subject, const int &prescaleFactor)
:	GripperEventServiceInHandlerCore(subject, prescaleFactor)
{
	std::cout << "constructor GripperEventServiceInHandler\n";
}
GripperEventServiceInHandler::~GripperEventServiceInHandler() 
{
	std::cout << "destructor GripperEventServiceInHandler\n";
}

void GripperEventServiceInHandler::on_GripperEventServiceIn(const Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult> &input)
{
	// implement business logic here
	// (do not use blocking calls here, otherwise this might block the InputPort GripperEventServiceIn)
}
