# includes for ComponentPlayerStageSimulatorROSExtension
GET_FILENAME_COMPONENT(ROS_DIR "${PROJECT_SOURCE_DIR}/../ROS" REALPATH)
IF(EXISTS ${ROS_DIR})
ADD_SUBDIRECTORY(${ROS_DIR}/src-gen/ ${PROJECT_BINARY_DIR}/ROS)
LIST(APPEND FURTHER_SRCS ${ROS_SRCS})
INCLUDE_DIRECTORIES(${ROS_INCLUDES})
ENDIF(EXISTS ${ROS_DIR})

# includes for PlainOpcUaComponentPlayerStageSimulatorExtension
GET_FILENAME_COMPONENT(PlainOPCUA_DIR "${PROJECT_SOURCE_DIR}/../plainOpcUa" REALPATH)
IF(EXISTS ${PlainOPCUA_DIR})
INCLUDE("${PlainOPCUA_DIR}/src-gen/ComponentPlayerStageSimulatorPlainOpcUa.cmake")
LIST(APPEND FURTHER_SRCS ${PLAIN_OPCUA_SRCS})
ENDIF(EXISTS ${PlainOPCUA_DIR})


