//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TRIGGERHANDLERCORE_HH
#define _TRIGGERHANDLERCORE_HH


#include <string>
#include <iostream>
#include <list>

class TriggerHandlerCore
{
	friend class ParamUpdateHandler;
	
public:
	TriggerHandlerCore() 
	{  
	}
	virtual ~TriggerHandlerCore() {  }

	// trigger user methods
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_BASE1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_DEPTHIMAGE1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_IR1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_LASER1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_LASER2() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_LASER3() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_MAP1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_RGB1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_SHOW_RGBD1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_BASE1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_DEPTHIMAGE1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_IR1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_LASER1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_LASER2() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_LASER3() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_MAP1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_RGB1() = 0;
	
		
		virtual void handleCommBasicObjects_VisualizationParams_STOP_RGBD1() = 0;
	
	// extended trigger user methods
	
private:
	// trigger internal methods
	void handleCommBasicObjects_VisualizationParams_SHOW_BASE1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_DEPTHIMAGE1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_IR1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_LASER1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_LASER2Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_LASER3Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_MAP1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_RGB1Core();
	void handleCommBasicObjects_VisualizationParams_SHOW_RGBD1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_BASE1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_DEPTHIMAGE1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_IR1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_LASER1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_LASER2Core();
	void handleCommBasicObjects_VisualizationParams_STOP_LASER3Core();
	void handleCommBasicObjects_VisualizationParams_STOP_MAP1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_RGB1Core();
	void handleCommBasicObjects_VisualizationParams_STOP_RGBD1Core();
	
	// extended trigger internal methods 
};

#endif // _TRIGGERHANDLERCORE_HH
