//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _NAVIGATIONPOSE2DSERVICEINHANDLER_HH
#define _NAVIGATIONPOSE2DSERVICEINHANDLER_HH
/*

#include "NavigationPose2DServiceInHandlerCore.hh"
	
class NavigationPose2DServiceInHandler  : public NavigationPose2DServiceInHandlerCore
{		
public:
	NavigationPose2DServiceInHandler(Smart::InputSubject<CommBasicObjects::CommNavigationPose2D> *subject, const int &prescaleFactor=1);
	virtual ~NavigationPose2DServiceInHandler();
	
	virtual void on_NavigationPose2DServiceIn(const CommBasicObjects::CommNavigationPose2D &input);
};
*/
#endif
