//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _MANIPULATOREVENTSERVICEINHANDLER_CORE_HH
#define _MANIPULATOREVENTSERVICEINHANDLER_CORE_HH

#include <aceSmartSoft.hh>

// include the main input-handler interface
#include "ManipulatorEventServiceInUpcallInterface.hh"
// include all other input interfaces (if any)

// include all interaction-observer interfaces
#include <ManipulatorEventServiceInHandlerObserverInterface.hh>

class ManipulatorEventServiceInHandlerCore
:	public Smart::InputTaskTrigger<Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult,SmartACE::EventId>>
,	public ManipulatorEventServiceInUpcallInterface
{
private:
	Smart::StatusCode updateStatus;
	Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult,SmartACE::EventId> lastUpdate;
	
	
	virtual void updateAllCommObjects();
	
	// internal input handling method
	virtual void handle_input(const Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult,SmartACE::EventId>& input) {
		this->updateAllCommObjects();
		// call the input handler method (which has to be implemented in derived classes)
		this->on_ManipulatorEventServiceIn(input);
		// notify all attached interaction observers
		this->notify_all_interaction_observers();
		// call implementation of base class
		Smart::InputTaskTrigger<Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult,SmartACE::EventId>>::handle_input(input);
	}
	
/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<ManipulatorEventServiceInHandlerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(ManipulatorEventServiceInHandlerObserverInterface *observer);
	void detach_interaction_observer(ManipulatorEventServiceInHandlerObserverInterface *observer);
	
protected:

public:
	ManipulatorEventServiceInHandlerCore(
		Smart::InputSubject<Smart::EventInputType<CommManipulatorObjects::CommManipulatorEventResult,SmartACE::EventId>> *subject,
		const int &prescaleFactor=1);
	virtual ~ManipulatorEventServiceInHandlerCore();
};
#endif
