//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentAprilTagDetector.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentAprilTagDetectorAcePortFactory.hh"

#include "MarkerListEventServiceOutEventTestHandler.hh"

// initialize static singleton pointer to zero
ComponentAprilTagDetector* ComponentAprilTagDetector::_componentAprilTagDetector = 0;

// constructor
ComponentAprilTagDetector::ComponentAprilTagDetector()
{
	std::cout << "constructor of ComponentAprilTagDetector\n";
	
	// set all pointer members to NULL
	//componentAprilTagDetector = NULL;
	//coordinationPort = NULL;
	detectorTask = NULL;
	detectorTaskTrigger = NULL;
	markerListDetectionServiceOut = NULL;
	markerListDetectionServiceOutWrapper = NULL;
	markerListEventServiceOut = NULL;
	markerListEventServiceOutWrapper = NULL;
	markerListEventServiceOutEventTestHandler = nullptr; 
	rGBImagePushServiceIn = NULL;
	rGBImagePushServiceInInputTaskTrigger = NULL;
	rGBImagePushServiceInUpcallManager = NULL;
	rGBImagePushServiceInInputCollector = NULL;
	rGBImagePushServiceOut = NULL;
	rGBImagePushServiceOutWrapper = NULL;
	stateChangeHandler = NULL;
	stateActivityManager = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	param = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentAprilTagDetector";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.markerListDetectionServiceOut.serviceName = "MarkerListDetectionServiceOut";
	connections.markerListDetectionServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.markerListEventServiceOut.serviceName = "MarkerListEventServiceOut";
	connections.markerListEventServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImagePushServiceOut.serviceName = "RGBImagePushServiceOut";
	connections.rGBImagePushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImagePushServiceIn.initialConnect = false;
	connections.rGBImagePushServiceIn.wiringName = "RGBImagePushServiceIn";
	connections.rGBImagePushServiceIn.serverName = "unknown";
	connections.rGBImagePushServiceIn.serviceName = "unknown";
	connections.rGBImagePushServiceIn.interval = 1;
	connections.rGBImagePushServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.detectorTask.minActFreq = 0.0;
	connections.detectorTask.maxActFreq = 0.0;
	// scheduling default parameters
	connections.detectorTask.scheduler = "DEFAULT";
	connections.detectorTask.priority = -1;
	connections.detectorTask.cpuAffinity = -1;
	
}

void ComponentAprilTagDetector::addPortFactory(const std::string &name, ComponentAprilTagDetectorPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentAprilTagDetector::addExtension(ComponentAprilTagDetectorExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentAprilTagDetector::getComponentImpl()
{
	return dynamic_cast<ComponentAprilTagDetectorAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentAprilTagDetector::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode ComponentAprilTagDetector::connectRGBImagePushServiceIn(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.rGBImagePushServiceIn.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = rGBImagePushServiceIn->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->rGBImagePushServiceIn->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	rGBImagePushServiceIn->subscribe(connections.rGBImagePushServiceIn.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentAprilTagDetector::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectRGBImagePushServiceIn(connections.rGBImagePushServiceIn.serverName, connections.rGBImagePushServiceIn.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentAprilTagDetector::startAllTasks() {
	// start task DetectorTask
	if(connections.detectorTask.scheduler != "DEFAULT") {
		ACE_Sched_Params detectorTask_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.detectorTask.scheduler == "FIFO") {
			detectorTask_SchedParams.policy(ACE_SCHED_FIFO);
			#if defined(ACE_HAS_PTHREADS)
				detectorTask_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
			#elif defined (ACE_HAS_WTHREADS)
				detectorTask_SchedParams.priority(THREAD_PRIORITY_IDLE);
			#endif
		} else if(connections.detectorTask.scheduler == "RR") {
			detectorTask_SchedParams.policy(ACE_SCHED_RR);
			#if defined(ACE_HAS_PTHREADS)
				detectorTask_SchedParams.priority(ACE_THR_PRI_RR_MIN);
			#elif defined (ACE_HAS_WTHREADS)
				detectorTask_SchedParams.priority(THREAD_PRIORITY_IDLE);
			#endif
		}
		detectorTask->start(detectorTask_SchedParams, connections.detectorTask.cpuAffinity);
	} else {
		detectorTask->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentAprilTagDetector::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentAprilTagDetector::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "RGBImagePushServiceIn") return rGBImagePushServiceInInputTaskTrigger;
	
	return NULL;
}


void ComponentAprilTagDetector::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		// print out the actual parameters which are used to initialize the component
		std::cout << " \nComponentDefinition Initial-Parameters:\n" << COMP->getParameters() << std::endl;
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentAprilTagDetectorPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentAprilTagDetectorAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentAprilTagDetector is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		markerListEventServiceOutEventTestHandler = std::make_shared<MarkerListEventServiceOutEventTestHandler>();
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		markerListDetectionServiceOut = portFactoryRegistry[connections.markerListDetectionServiceOut.roboticMiddleware]->createMarkerListDetectionServiceOut(connections.markerListDetectionServiceOut.serviceName);
		markerListDetectionServiceOutWrapper = new MarkerListDetectionServiceOutWrapper(markerListDetectionServiceOut);
		markerListEventServiceOutEventTestHandler = std::make_shared<MarkerListEventServiceOutEventTestHandler>();
		markerListEventServiceOut = portFactoryRegistry[connections.markerListEventServiceOut.roboticMiddleware]->createMarkerListEventServiceOut(connections.markerListEventServiceOut.serviceName, markerListEventServiceOutEventTestHandler);
		markerListEventServiceOutWrapper = new MarkerListEventServiceOutWrapper(markerListEventServiceOut);
		rGBImagePushServiceOut = portFactoryRegistry[connections.rGBImagePushServiceOut.roboticMiddleware]->createRGBImagePushServiceOut(connections.rGBImagePushServiceOut.serviceName);
		rGBImagePushServiceOutWrapper = new RGBImagePushServiceOutWrapper(rGBImagePushServiceOut);
		
		// create client ports
		rGBImagePushServiceIn = portFactoryRegistry[connections.rGBImagePushServiceIn.roboticMiddleware]->createRGBImagePushServiceIn();
		
		// create InputTaskTriggers and UpcallManagers
		rGBImagePushServiceInInputCollector = new RGBImagePushServiceInInputCollector(rGBImagePushServiceIn);
		rGBImagePushServiceInInputTaskTrigger = new Smart::InputTaskTrigger<DomainVision::CommVideoImage>(rGBImagePushServiceInInputCollector);
		rGBImagePushServiceInUpcallManager = new RGBImagePushServiceInUpcallManager(rGBImagePushServiceInInputCollector);
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateActivityManager = new StateActivityManager(stateChangeHandler);
		stateSlave = new SmartACE::StateSlave(component, stateActivityManager);
		if (stateSlave->defineStates("Active" ,"active") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion Active.active" << std::endl;
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.rGBImagePushServiceIn.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainVision::CommVideoImage>*>(rGBImagePushServiceIn)->add(wiringSlave, connections.rGBImagePushServiceIn.wiringName);
		}
		
		// create parameter slave
		param = new SmartACE::ParameterSlave(component, &paramHandler);
		
		
		// create Task DetectorTask
		detectorTask = new DetectorTask(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.detectorTask.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = (int)(1000.0*1000.0 / connections.detectorTask.periodicActFreq);
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(detectorTask);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				detectorTaskTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task DetectorTask" << std::endl;
			}
		} else if(connections.detectorTask.trigger == "DataTriggered") {
			detectorTaskTrigger = getInputTaskTriggerFromString(connections.detectorTask.inPortRef);
			if(detectorTaskTrigger != NULL) {
				detectorTaskTrigger->attach(detectorTask, connections.detectorTask.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.detectorTask.inPortRef << " as activation source for Task DetectorTask" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentAprilTagDetector::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentAprilTagDetector::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(detectorTaskTrigger != NULL){
		detectorTaskTrigger->detach(detectorTask);
		delete detectorTask;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete rGBImagePushServiceInInputTaskTrigger;
	delete rGBImagePushServiceInUpcallManager;
	delete rGBImagePushServiceInInputCollector;

	// destroy client ports
	delete rGBImagePushServiceIn;

	// destroy request-handlers

	// destroy server ports
	delete markerListDetectionServiceOutWrapper;
	delete markerListDetectionServiceOut;
	delete markerListEventServiceOutWrapper;
	delete markerListEventServiceOut;
	delete rGBImagePushServiceOutWrapper;
	delete rGBImagePushServiceOut;
	
	// destroy event-test handlers (if needed)
	markerListEventServiceOutEventTestHandler;
	
	delete stateSlave;
	delete stateActivityManager;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	delete param;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
}

void ComponentAprilTagDetector::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentAprilTagDetector.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentAprilTagDetector.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentAprilTagDetector.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client RGBImagePushServiceIn
		parameter.getBoolean("RGBImagePushServiceIn", "initialConnect", connections.rGBImagePushServiceIn.initialConnect);
		parameter.getString("RGBImagePushServiceIn", "serviceName", connections.rGBImagePushServiceIn.serviceName);
		parameter.getString("RGBImagePushServiceIn", "serverName", connections.rGBImagePushServiceIn.serverName);
		parameter.getString("RGBImagePushServiceIn", "wiringName", connections.rGBImagePushServiceIn.wiringName);
		parameter.getInteger("RGBImagePushServiceIn", "interval", connections.rGBImagePushServiceIn.interval);
		if(parameter.checkIfParameterExists("RGBImagePushServiceIn", "roboticMiddleware")) {
			parameter.getString("RGBImagePushServiceIn", "roboticMiddleware", connections.rGBImagePushServiceIn.roboticMiddleware);
		}
		
		// load parameters for server MarkerListDetectionServiceOut
		parameter.getString("MarkerListDetectionServiceOut", "serviceName", connections.markerListDetectionServiceOut.serviceName);
		if(parameter.checkIfParameterExists("MarkerListDetectionServiceOut", "roboticMiddleware")) {
			parameter.getString("MarkerListDetectionServiceOut", "roboticMiddleware", connections.markerListDetectionServiceOut.roboticMiddleware);
		}
		// load parameters for server MarkerListEventServiceOut
		parameter.getString("MarkerListEventServiceOut", "serviceName", connections.markerListEventServiceOut.serviceName);
		if(parameter.checkIfParameterExists("MarkerListEventServiceOut", "roboticMiddleware")) {
			parameter.getString("MarkerListEventServiceOut", "roboticMiddleware", connections.markerListEventServiceOut.roboticMiddleware);
		}
		// load parameters for server RGBImagePushServiceOut
		parameter.getString("RGBImagePushServiceOut", "serviceName", connections.rGBImagePushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("RGBImagePushServiceOut", "roboticMiddleware")) {
			parameter.getString("RGBImagePushServiceOut", "roboticMiddleware", connections.rGBImagePushServiceOut.roboticMiddleware);
		}
		
		// load parameters for task DetectorTask
		parameter.getDouble("DetectorTask", "minActFreqHz", connections.detectorTask.minActFreq);
		parameter.getDouble("DetectorTask", "maxActFreqHz", connections.detectorTask.maxActFreq);
		parameter.getString("DetectorTask", "triggerType", connections.detectorTask.trigger);
		if(connections.detectorTask.trigger == "PeriodicTimer") {
			parameter.getDouble("DetectorTask", "periodicActFreqHz", connections.detectorTask.periodicActFreq);
		} else if(connections.detectorTask.trigger == "DataTriggered") {
			parameter.getString("DetectorTask", "inPortRef", connections.detectorTask.inPortRef);
			parameter.getInteger("DetectorTask", "prescale", connections.detectorTask.prescale);
		}
		if(parameter.checkIfParameterExists("DetectorTask", "scheduler")) {
			parameter.getString("DetectorTask", "scheduler", connections.detectorTask.scheduler);
		}
		if(parameter.checkIfParameterExists("DetectorTask", "priority")) {
			parameter.getInteger("DetectorTask", "priority", connections.detectorTask.priority);
		}
		if(parameter.checkIfParameterExists("DetectorTask", "cpuAffinity")) {
			parameter.getInteger("DetectorTask", "cpuAffinity", connections.detectorTask.cpuAffinity);
		}
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
		paramHandler.loadParameter(parameter);
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
