//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentExerciseApproachCylinderAcePortFactory.hh"

// create a static instance of the default AcePortFactory
static ComponentExerciseApproachCylinderAcePortFactory acePortFactory;

ComponentExerciseApproachCylinderAcePortFactory::ComponentExerciseApproachCylinderAcePortFactory()
{  
	componentImpl = 0;
	ComponentExerciseApproachCylinder::instance()->addPortFactory("ACE_SmartSoft", this);
}

ComponentExerciseApproachCylinderAcePortFactory::~ComponentExerciseApproachCylinderAcePortFactory()
{  }

void ComponentExerciseApproachCylinderAcePortFactory::initialize(ComponentExerciseApproachCylinder *component, int argc, char* argv[])
{
	if(component->connections.component.defaultScheduler != "DEFAULT") {
		ACE_Sched_Params sched_params(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(component->connections.component.defaultScheduler == "FIFO") {
			sched_params.policy(ACE_SCHED_FIFO);
			#if defined(ACE_HAS_PTHREADS)
				sched_params.priority(ACE_THR_PRI_FIFO_MIN);
			#elif defined (ACE_HAS_WTHREADS)
				sched_params.priority(THREAD_PRIORITY_IDLE);
			#endif
		} else if(component->connections.component.defaultScheduler == "RR") {
			sched_params.policy(ACE_SCHED_RR);
			#if defined(ACE_HAS_PTHREADS)
				sched_params.priority(ACE_THR_PRI_RR_MIN);
			#elif defined (ACE_HAS_WTHREADS)
				sched_params.priority(THREAD_PRIORITY_IDLE);
			#endif
		}
		// create new instance of the SmartSoft component with customized scheuling parameters 
		componentImpl = new ComponentExerciseApproachCylinderImpl(component->connections.component.name, argc, argv, sched_params);
	} else {
		// create new instance of the SmartSoft component
		componentImpl = new ComponentExerciseApproachCylinderImpl(component->connections.component.name, argc, argv);
	}
}

int ComponentExerciseApproachCylinderAcePortFactory::onStartup()
{
	return componentImpl->startComponentInfrastructure();
}

Smart::IPushClientPattern<CommBasicObjects::CommMobileLaserScan> * ComponentExerciseApproachCylinderAcePortFactory::createLaserServiceIn()
{
	return new SmartACE::PushClient<CommBasicObjects::CommMobileLaserScan>(componentImpl);
}

Smart::ISendClientPattern<CommBasicObjects::CommNavigationVelocity> * ComponentExerciseApproachCylinderAcePortFactory::createNavigationVelocityServiceOut()
{
	return new SmartACE::SendClient<CommBasicObjects::CommNavigationVelocity>(componentImpl);
}



SmartACE::SmartComponent* ComponentExerciseApproachCylinderAcePortFactory::getComponentImpl()
{
	return componentImpl;
}

int ComponentExerciseApproachCylinderAcePortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	componentImpl->stopComponentInfrastructure(timeoutTime);
	return 0;
}

void ComponentExerciseApproachCylinderAcePortFactory::destroy()
{
	// clean-up component's internally used resources (internally used communication middleware) 
	componentImpl->cleanUpComponentResources();
	delete componentImpl;
}
