//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENTREALSENSEPERSONTRACKER_OPC_UA_BACKEND_PORTFACTORY_HH_
#define COMPONENTREALSENSEPERSONTRACKER_OPC_UA_BACKEND_PORTFACTORY_HH_

// include the main component-definition class
#include "ComponentRealSensePersonTrackerPortFactoryInterface.hh"

#include <thread>
#include <chrono>

// include SeRoNetSDK library
#include <SeRoNetSDK/SeRoNet/Utils/Task.hpp>
#include <SeRoNetSDK/SeRoNet/Utils/Component.hpp>

class ComponentRealSensePersonTrackerOpcUaBackendPortFactory: public ComponentRealSensePersonTrackerPortFactoryInterface
{
private:
	// internal component instance
	SeRoNet::Utils::Component *componentImpl;
	
	// component thread
	std::thread component_thread;
	
	// internal component thread method
	int task_execution();
public:
	ComponentRealSensePersonTrackerOpcUaBackendPortFactory();
	virtual ~ComponentRealSensePersonTrackerOpcUaBackendPortFactory();

	virtual void initialize(ComponentRealSensePersonTracker *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<DomainVision::CommRGBDImage> * createRealSenseClient() override;
	
	virtual Smart::IEventServerPattern<CommTrackingObjects::CommPersonLostEventParameter, CommTrackingObjects::CommPersonLostEventResult, CommTrackingObjects::PersonLostEventState> * createPersonLostEventServer(const std::string &serviceName, std::shared_ptr<Smart::IEventTestHandler<CommTrackingObjects::CommPersonLostEventParameter, CommTrackingObjects::CommPersonLostEventResult, CommTrackingObjects::PersonLostEventState>> personLostEventServerEventTestHandler) override;
	virtual Smart::IPushServerPattern<DomainVision::CommVideoImage> * createRgb_video_server(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<CommTrackingObjects::CommTrackingGoal> * createTrackingGoalServer(const std::string &serviceName) override;
	
	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* COMPONENTREALSENSEPERSONTRACKER_SERONET_SDK_PORTFACTORY_HH_ */
