//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "ComponentWebInterfaceComissioningOpcUaBackendPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "CommBasicObjectsOpcUa/CommSkillMsgOpcUa.hh"

// create a static instance of the OpcUaBackendPortFactory
static ComponentWebInterfaceComissioningOpcUaBackendPortFactory OpcUaBackendPortFactory;

ComponentWebInterfaceComissioningOpcUaBackendPortFactory::ComponentWebInterfaceComissioningOpcUaBackendPortFactory()
{  
	componentImpl = 0;
	ComponentWebInterfaceComissioning::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

ComponentWebInterfaceComissioningOpcUaBackendPortFactory::~ComponentWebInterfaceComissioningOpcUaBackendPortFactory()
{  }

void ComponentWebInterfaceComissioningOpcUaBackendPortFactory::initialize(ComponentWebInterfaceComissioning *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int ComponentWebInterfaceComissioningOpcUaBackendPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&ComponentWebInterfaceComissioningOpcUaBackendPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}


Smart::IEventServerPattern<CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg> * ComponentWebInterfaceComissioningOpcUaBackendPortFactory::createSequencerEventServer(const std::string &serviceName, std::shared_ptr<Smart::IEventTestHandler<CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg>> sequencerEventServerEventTestHandler)
{
	return new SeRoNet::OPCUA::Server::EventServer<CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg, CommBasicObjects::CommSkillMsg>(componentImpl, serviceName, sequencerEventServerEventTestHandler);
}

Smart::ISendServerPattern<CommBasicObjects::CommSkillMsg> * ComponentWebInterfaceComissioningOpcUaBackendPortFactory::createSequencerSendServer(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::SendServer<CommBasicObjects::CommSkillMsg>(componentImpl, serviceName);
}


int ComponentWebInterfaceComissioningOpcUaBackendPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int ComponentWebInterfaceComissioningOpcUaBackendPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void ComponentWebInterfaceComissioningOpcUaBackendPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
