//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "BaseFakeActivity.hh"
#include "ComponentRosBaseFake.hh"

#include <iostream>

BaseFakeActivity::BaseFakeActivity(SmartACE::SmartComponent *comp) 
:	BaseFakeActivityCore(comp)
{
	std::cout << "constructor BaseFakeActivity\n";
}
BaseFakeActivity::~BaseFakeActivity() 
{
	std::cout << "destructor BaseFakeActivity\n";
}


void BaseFakeActivity::on_NavigationVelocityServiceIn(const CommBasicObjects::CommNavigationVelocity &input)
{
	// upcall triggered from InputPort NavigationVelocityServiceIn
	// - use a local mutex here, because this upcal is called asynchroneously from outside of this task
	// - do not use longer blocking calls here since this upcall blocks the InputPort NavigationVelocityServiceIn
	// - if you need to implement a long-running procedure, do so within the on_execute() method and in
	//   there, use the method navigationVelocityServiceInGetUpdate(input) to get a copy of the input object

	geometry_msgs::Twist twist_msg;
	twist_msg.linear.x = input.get_vX();
	twist_msg.linear.y = input.get_vY();
	twist_msg.angular.z = input.get_omega();

	std::cout << "publishing twist: \n" << twist_msg << std::endl;
	COMP -> rosPorts -> twist_pub.publish(twist_msg);
	//twist_pub.publish(twist);
}

int BaseFakeActivity::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	return 0;
}
int BaseFakeActivity::on_execute()
{
	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
	// to get the incoming data, use this methods:
	Smart::StatusCode status;
	CommBasicObjects::CommNavigationVelocity navigationVelocityServiceInObject;
	status = this->navigationVelocityServiceInGetUpdate(navigationVelocityServiceInObject);
	if(status != Smart::SMART_OK) {
		std::cerr << status << std::endl;
		// return 0;
	} else {
		std::cout << "received: " << navigationVelocityServiceInObject << std::endl;
	}

	std::cout << "Hello from BaseFakeActivity " << std::endl;

	CommBasicObjects::CommBaseState baseState;
	status = this->baseStateServiceOutPut(baseState);
	std::cout << "sent baseState :\n " << status << std::endl;

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int BaseFakeActivity::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
