//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TASKEVENTOUTWRAPPER_HH
#define _TASKEVENTOUTWRAPPER_HH

#include <mutex>
#include "aceSmartSoft.hh"

// include communication objects
#include <CommBasicObjects/CommTaskEventState.hh>
#include <CommBasicObjects/CommTaskEventStateACE.hh>
#include <CommBasicObjects/CommTaskMessage.hh>
#include <CommBasicObjects/CommTaskMessageACE.hh>


class TaskEventOutWrapper
{
private:
	std::mutex update_mutex;
	Smart::StatusCode update_status;
	
	CommBasicObjects::CommTaskEventState updateEventState;
	CommBasicObjects::CommTaskMessage updateEvent;
	CommBasicObjects::CommTaskMessage updateActivation;
	
	Smart::IEventServerPattern<CommBasicObjects::CommTaskMessage, CommBasicObjects::CommTaskMessage, CommBasicObjects::CommTaskEventState> *taskEventOut;
	
public:
	TaskEventOutWrapper(Smart::IEventServerPattern<CommBasicObjects::CommTaskMessage, CommBasicObjects::CommTaskMessage, CommBasicObjects::CommTaskEventState> *taskEventOut);
	virtual ~TaskEventOutWrapper();
	
	Smart::StatusCode put(CommBasicObjects::CommTaskEventState &eventState);
	
	Smart::StatusCode getLatestUpdate(CommBasicObjects::CommTaskEventState &eventState);
	
};

#endif // _TASKEVENTOUTWRAPPER_HH
