//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TASKRESULTOUTWRAPPER_HH
#define _TASKRESULTOUTWRAPPER_HH

#include <mutex>
#include "aceSmartSoft.hh"

// include communication objects
#include <CommBasicObjects/CommTaskMessage.hh>
#include <CommBasicObjects/CommTaskMessageACE.hh>


class TaskResultOutWrapper
{
private:
	std::mutex update_mutex;
	Smart::StatusCode update_status;
	
	CommBasicObjects::CommTaskMessage updateData;
	
	Smart::IPushServerPattern<CommBasicObjects::CommTaskMessage> *taskResultOut;
	
public:
	TaskResultOutWrapper(Smart::IPushServerPattern<CommBasicObjects::CommTaskMessage> *taskResultOut);
	virtual ~TaskResultOutWrapper();
	
	Smart::StatusCode put(CommBasicObjects::CommTaskMessage &taskResultOutDataObject);
	
	Smart::StatusCode getLatestUpdate(CommBasicObjects::CommTaskMessage &taskResultOutDataObject);
	
};

#endif // _TASKRESULTOUTWRAPPER_HH
