//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _DEPTHPUSHNEWESTSERVERWRAPPER_HH
#define _DEPTHPUSHNEWESTSERVERWRAPPER_HH

#include <mutex>
#include "aceSmartSoft.hh"

// include communication objects
#include <DomainVision/CommDepthImage.hh>
#include <DomainVision/CommDepthImageACE.hh>


class DepthPushNewestServerWrapper
{
private:
	std::mutex update_mutex;
	Smart::StatusCode update_status;
	
	DomainVision::CommDepthImage updateData;
	
	Smart::IPushServerPattern<DomainVision::CommDepthImage> *depthPushNewestServer;
	
public:
	DepthPushNewestServerWrapper(Smart::IPushServerPattern<DomainVision::CommDepthImage> *depthPushNewestServer);
	virtual ~DepthPushNewestServerWrapper();
	
	Smart::StatusCode put(DomainVision::CommDepthImage &depthPushNewestServerDataObject);
	
	Smart::StatusCode getLatestUpdate(DomainVision::CommDepthImage &depthPushNewestServerDataObject);
	
};

#endif // _DEPTHPUSHNEWESTSERVERWRAPPER_HH
