//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "VisualMarkerMapTask.hh"
#include "ComponentVisualization.hh"

#include <iostream>

VisualMarkerMapTask::VisualMarkerMapTask(SmartACE::SmartComponent *comp) 
:	VisualMarkerMapTaskCore(comp)
{
	std::cout << "constructor VisualMarkerMapTask\n";
}
VisualMarkerMapTask::~VisualMarkerMapTask() 
{
	std::cout << "destructor VisualMarkerMapTask\n";
}

int VisualMarkerMapTask::connectServices(){
	std::cout << "connecting to: " << COMP->connections.visualMarkers.serverName << "; " << COMP->connections.visualMarkers.serviceName << std::endl;
	Smart::StatusCode status = COMP->visualMarkers->connect(COMP->connections.visualMarkers.serverName, COMP->connections.visualMarkers.serviceName);
	while (status != Smart::SMART_OK) {
		usleep(500000);
		status = COMP->visualMarkers->connect(COMP->connections.visualMarkers.serverName, COMP->connections.visualMarkers.serviceName);
	}
	std::cout << COMP->connections.visualMarkers.serverName << "; " << COMP->connections.visualMarkers.serviceName << " connected.\n";
	return 0;
}


int VisualMarkerMapTask::disconnectServices(){
	COMP->visualMarkers->disconnect();
	return 0;
}


int VisualMarkerMapTask::on_entry()
{
	mapVis = new VisualLocalizationMapVisualization(COMP->getWindow3d(), "vismap");
	return (mapVis != 0) ? 0 : 1;
}
int VisualMarkerMapTask::on_execute()
{
	Smart::StatusCode status = COMP->visualMarkers->query(request, map);
	if (status == Smart::SMART_OK) {
		if(map.getFeaturesSize()>0)
			mapVis->displayMap(map);
	} else {
		std::cout << "VisualMarkerMapTask :: problem in receiving messages : " << Smart::StatusCodeConversion(status)<<std::endl;
		mapVis->clear();
	}

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int VisualMarkerMapTask::on_exit()
{
	delete mapVis;
	return 0;
}
