//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TRAFFICLIGHTSERVICEIN_UPCALL_MANAGER_HH
#define _TRAFFICLIGHTSERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "TrafficLightServiceInUpcallInterface.hh"

/** TrafficLightServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort TrafficLightServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class TrafficLightServiceInUpcallManager
:	public Smart::IInputHandler<DomainHMI::CommTrafficLight>
{
private:
	// list of associated updalls
	std::list<TrafficLightServiceInUpcallInterface*> upcalls;

	// call the on_TrafficLightServiceIn of all the attached TrafficLightServiceInUpcallInterfaces
	void notify_upcalls(const DomainHMI::CommTrafficLight &input);
	
protected:
	virtual void handle_input(const DomainHMI::CommTrafficLight &input) {
		// relay input-handling to all attached TrafficLightServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	TrafficLightServiceInUpcallManager(
		Smart::InputSubject<DomainHMI::CommTrafficLight> *subject,
		const int &prescaleFactor=1
	);
	virtual ~TrafficLightServiceInUpcallManager();
	
	void attach(TrafficLightServiceInUpcallInterface *upcall);
	void detach(TrafficLightServiceInUpcallInterface *upcall);
};

#endif
