//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENTTRAFFICLIGHTTEST_HH
#define _COMPONENTTRAFFICLIGHTTEST_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "ComponentTrafficLightTestCore.hh"

#include "ComponentTrafficLightTestPortFactoryInterface.hh"
#include "ComponentTrafficLightTestExtension.hh"

// forward declarations
class ComponentTrafficLightTestPortFactoryInterface;
class ComponentTrafficLightTestExtension;

// includes for OpcUaBackendComponentGeneratorExtension

// includes for ComponentTrafficLightTestROSExtension

// includes for PlainOpcUaComponentTrafficLightTestExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <DomainHMI/CommTrafficLight.hh>
#include <DomainHMI/CommTrafficLightACE.hh>

// include tasks
#include "GenerateOut.hh"
// include UpcallManagers

// include input-handler(s)
// include request-handler(s)

// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP ComponentTrafficLightTest::instance()

class ComponentTrafficLightTest : public ComponentTrafficLightTestCore {
private:
	static ComponentTrafficLightTest *_componentTrafficLightTest;
	
	// constructor
	ComponentTrafficLightTest();
	
	// copy-constructor
	ComponentTrafficLightTest(const ComponentTrafficLightTest& cc);
	
	// destructor
	~ComponentTrafficLightTest() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, ComponentTrafficLightTestPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, ComponentTrafficLightTestExtension*> componentExtensionRegistry;
	
public:
	
	// define tasks
	Smart::TaskTriggerSubject* generateOutTrigger;
	GenerateOut *generateOut;
	
	// define input-ports
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	Smart::ISendClientPattern<DomainHMI::CommTrafficLight> *trafficLightServiceOut;
	
	// define answer-ports
	
	// define request-handlers
	
	// definitions of OpcUaBackendComponentGeneratorExtension
	
	// definitions of ComponentTrafficLightTestROSExtension
	
	// definitions of PlainOpcUaComponentTrafficLightTestExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, ComponentTrafficLightTestPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(ComponentTrafficLightTestExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	
	Smart::StatusCode connectTrafficLightServiceOut(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static ComponentTrafficLightTest* instance()
	{
		if(_componentTrafficLightTest == 0) {
			_componentTrafficLightTest = new ComponentTrafficLightTest();
		}
		return _componentTrafficLightTest;
	}
	
	static void deleteInstance() {
		if(_componentTrafficLightTest != 0) {
			delete _componentTrafficLightTest;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct GenerateOut_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} generateOut;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
	
		//--- client port parameter ---
		struct TrafficLightServiceOut_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} trafficLightServiceOut;
		
		// -- parameters for OpcUaBackendComponentGeneratorExtension
		
		// -- parameters for ComponentTrafficLightTestROSExtension
		
		// -- parameters for PlainOpcUaComponentTrafficLightTestExtension
		
	} connections;
};
#endif
