//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentRobotinoIRServer.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentRobotinoIRServerAcePortFactory.hh"


// initialize static singleton pointer to zero
ComponentRobotinoIRServer* ComponentRobotinoIRServer::_componentRobotinoIRServer = 0;

// constructor
ComponentRobotinoIRServer::ComponentRobotinoIRServer()
{
	std::cout << "constructor of ComponentRobotinoIRServer\n";
	
	// set all pointer members to NULL
	additionalIRScanPushOut = NULL;
	additionalIRScanPushOutWrapper = NULL;
	baseStateServiceIn = NULL;
	baseStateServiceInInputTaskTrigger = NULL;
	baseStateServiceInUpcallManager = NULL;
	baseStateServiceInInputCollector = NULL;
	//coordinationPort = NULL;
	//coordinationPort = NULL;
	iRTask = NULL;
	iRTaskTrigger = NULL;
	mobileIRPushOut = NULL;
	mobileIRPushOutWrapper = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	param = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentRobotinoIRServer";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.additionalIRScanPushOut.serviceName = "AdditionalIRScanPushOut";
	connections.additionalIRScanPushOut.roboticMiddleware = "ACE_SmartSoft";
	connections.mobileIRPushOut.serviceName = "MobileIRPushOut";
	connections.mobileIRPushOut.roboticMiddleware = "ACE_SmartSoft";
	connections.baseStateServiceIn.initialConnect = false;
	connections.baseStateServiceIn.wiringName = "BaseStateServiceIn";
	connections.baseStateServiceIn.serverName = "unknown";
	connections.baseStateServiceIn.serviceName = "unknown";
	connections.baseStateServiceIn.interval = 1;
	connections.baseStateServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.iRTask.minActFreq = 0.0;
	connections.iRTask.maxActFreq = 0.0;
	connections.iRTask.trigger = "PeriodicTimer";
	connections.iRTask.periodicActFreq = 20.0;
	// scheduling default parameters
	connections.iRTask.scheduler = "DEFAULT";
	connections.iRTask.priority = -1;
	connections.iRTask.cpuAffinity = -1;
	
	// initialize members of ComponentRobotinoIRServerROS1InterfacesExtension
	
	// initialize members of ComponentRobotinoIRServerRestInterfacesExtension
	
	// initialize members of PlainOpcUaComponentRobotinoIRServerExtension
	
}

void ComponentRobotinoIRServer::addPortFactory(const std::string &name, ComponentRobotinoIRServerPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentRobotinoIRServer::addExtension(ComponentRobotinoIRServerExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentRobotinoIRServer::getComponentImpl()
{
	return dynamic_cast<ComponentRobotinoIRServerAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentRobotinoIRServer::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode ComponentRobotinoIRServer::connectBaseStateServiceIn(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.baseStateServiceIn.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = baseStateServiceIn->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->baseStateServiceIn->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	baseStateServiceIn->subscribe(connections.baseStateServiceIn.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentRobotinoIRServer::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectBaseStateServiceIn(connections.baseStateServiceIn.serverName, connections.baseStateServiceIn.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentRobotinoIRServer::startAllTasks() {
	// start task IRTask
	if(connections.iRTask.scheduler != "DEFAULT") {
		ACE_Sched_Params iRTask_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.iRTask.scheduler == "FIFO") {
			iRTask_SchedParams.policy(ACE_SCHED_FIFO);
			iRTask_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.iRTask.scheduler == "RR") {
			iRTask_SchedParams.policy(ACE_SCHED_RR);
			iRTask_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		iRTask->start(iRTask_SchedParams, connections.iRTask.cpuAffinity);
	} else {
		iRTask->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentRobotinoIRServer::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentRobotinoIRServer::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "BaseStateServiceIn") return baseStateServiceInInputTaskTrigger;
	
	return NULL;
}


void ComponentRobotinoIRServer::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		// print out the actual parameters which are used to initialize the component
		std::cout << " \nComponentDefinition Initial-Parameters:\n" << COMP->getParameters() << std::endl;
		
		// initializations of ComponentRobotinoIRServerROS1InterfacesExtension
		
		// initializations of ComponentRobotinoIRServerRestInterfacesExtension
		
		// initializations of PlainOpcUaComponentRobotinoIRServerExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentRobotinoIRServerPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentRobotinoIRServerAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentRobotinoIRServer is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		additionalIRScanPushOut = portFactoryRegistry[connections.additionalIRScanPushOut.roboticMiddleware]->createAdditionalIRScanPushOut(connections.additionalIRScanPushOut.serviceName);
		additionalIRScanPushOutWrapper = new AdditionalIRScanPushOutWrapper(additionalIRScanPushOut);
		mobileIRPushOut = portFactoryRegistry[connections.mobileIRPushOut.roboticMiddleware]->createMobileIRPushOut(connections.mobileIRPushOut.serviceName);
		mobileIRPushOutWrapper = new MobileIRPushOutWrapper(mobileIRPushOut);
		
		// create client ports
		baseStateServiceIn = portFactoryRegistry[connections.baseStateServiceIn.roboticMiddleware]->createBaseStateServiceIn();
		
		// create InputTaskTriggers and UpcallManagers
		baseStateServiceInInputCollector = new BaseStateServiceInInputCollector(baseStateServiceIn);
		baseStateServiceInInputTaskTrigger = new Smart::InputTaskTrigger<CommBasicObjects::CommBaseState>(baseStateServiceInInputCollector);
		baseStateServiceInUpcallManager = new BaseStateServiceInUpcallManager(baseStateServiceInInputCollector);
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		if (stateSlave->defineStates("FetchAdditionalIR" ,"fetchAdditionalIR") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion FetchAdditionalIR.fetchAdditionalIR" << std::endl;
		if (stateSlave->defineStates("FetchBoth" ,"fetchBoth") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion FetchBoth.fetchBoth" << std::endl;
		if (stateSlave->defineStates("FetchIR" ,"fetchIR") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion FetchIR.fetchIR" << std::endl;
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.baseStateServiceIn.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<CommBasicObjects::CommBaseState>*>(baseStateServiceIn)->add(wiringSlave, connections.baseStateServiceIn.wiringName);
		}
		
		// create parameter slave
		param = new SmartACE::ParameterSlave(component, &paramHandler);
		
		
		// create Task IRTask
		iRTask = new IRTask(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.iRTask.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.iRTask.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(iRTask);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				iRTaskTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task IRTask" << std::endl;
			}
		} else if(connections.iRTask.trigger == "DataTriggered") {
			iRTaskTrigger = getInputTaskTriggerFromString(connections.iRTask.inPortRef);
			if(iRTaskTrigger != NULL) {
				iRTaskTrigger->attach(iRTask, connections.iRTask.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.iRTask.inPortRef << " as activation source for Task IRTask" << std::endl;
			}
		} else
		{
			// setup default task-trigger as PeriodicTimer
			Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
			int microseconds = 1000*1000 / 20.0;
			if(microseconds > 0) {
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				triggerPtr->attach(iRTask);
				// store trigger in class member
				iRTaskTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task IRTask" << std::endl;
			}
		}
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentRobotinoIRServer::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentRobotinoIRServer::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(iRTaskTrigger != NULL){
		iRTaskTrigger->detach(iRTask);
		delete iRTask;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete baseStateServiceInInputTaskTrigger;
	delete baseStateServiceInUpcallManager;
	delete baseStateServiceInInputCollector;

	// destroy client ports
	delete baseStateServiceIn;

	// destroy server ports
	delete additionalIRScanPushOutWrapper;
	delete additionalIRScanPushOut;
	delete mobileIRPushOutWrapper;
	delete mobileIRPushOut;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	delete param;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of ComponentRobotinoIRServerROS1InterfacesExtension
	
	// destruction of ComponentRobotinoIRServerRestInterfacesExtension
	
	// destruction of PlainOpcUaComponentRobotinoIRServerExtension
	
}

void ComponentRobotinoIRServer::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentRobotinoIRServer.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentRobotinoIRServer.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentRobotinoIRServer.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client BaseStateServiceIn
		parameter.getBoolean("BaseStateServiceIn", "initialConnect", connections.baseStateServiceIn.initialConnect);
		parameter.getString("BaseStateServiceIn", "serviceName", connections.baseStateServiceIn.serviceName);
		parameter.getString("BaseStateServiceIn", "serverName", connections.baseStateServiceIn.serverName);
		parameter.getString("BaseStateServiceIn", "wiringName", connections.baseStateServiceIn.wiringName);
		parameter.getInteger("BaseStateServiceIn", "interval", connections.baseStateServiceIn.interval);
		if(parameter.checkIfParameterExists("BaseStateServiceIn", "roboticMiddleware")) {
			parameter.getString("BaseStateServiceIn", "roboticMiddleware", connections.baseStateServiceIn.roboticMiddleware);
		}
		
		// load parameters for server AdditionalIRScanPushOut
		parameter.getString("AdditionalIRScanPushOut", "serviceName", connections.additionalIRScanPushOut.serviceName);
		if(parameter.checkIfParameterExists("AdditionalIRScanPushOut", "roboticMiddleware")) {
			parameter.getString("AdditionalIRScanPushOut", "roboticMiddleware", connections.additionalIRScanPushOut.roboticMiddleware);
		}
		// load parameters for server MobileIRPushOut
		parameter.getString("MobileIRPushOut", "serviceName", connections.mobileIRPushOut.serviceName);
		if(parameter.checkIfParameterExists("MobileIRPushOut", "roboticMiddleware")) {
			parameter.getString("MobileIRPushOut", "roboticMiddleware", connections.mobileIRPushOut.roboticMiddleware);
		}
		
		// load parameters for task IRTask
		parameter.getDouble("IRTask", "minActFreqHz", connections.iRTask.minActFreq);
		parameter.getDouble("IRTask", "maxActFreqHz", connections.iRTask.maxActFreq);
		parameter.getString("IRTask", "triggerType", connections.iRTask.trigger);
		if(connections.iRTask.trigger == "PeriodicTimer") {
			parameter.getDouble("IRTask", "periodicActFreqHz", connections.iRTask.periodicActFreq);
		} else if(connections.iRTask.trigger == "DataTriggered") {
			parameter.getString("IRTask", "inPortRef", connections.iRTask.inPortRef);
			parameter.getInteger("IRTask", "prescale", connections.iRTask.prescale);
		}
		if(parameter.checkIfParameterExists("IRTask", "scheduler")) {
			parameter.getString("IRTask", "scheduler", connections.iRTask.scheduler);
		}
		if(parameter.checkIfParameterExists("IRTask", "priority")) {
			parameter.getInteger("IRTask", "priority", connections.iRTask.priority);
		}
		if(parameter.checkIfParameterExists("IRTask", "cpuAffinity")) {
			parameter.getInteger("IRTask", "cpuAffinity", connections.iRTask.cpuAffinity);
		}
		
		// load parameters for ComponentRobotinoIRServerROS1InterfacesExtension
		
		// load parameters for ComponentRobotinoIRServerRestInterfacesExtension
		
		// load parameters for PlainOpcUaComponentRobotinoIRServerExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
		paramHandler.loadParameter(parameter);
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
