//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef SMARTMAPPERGRIDMAP_PORTFACTORYINTERFACE_HH_
#define SMARTMAPPERGRIDMAP_PORTFACTORYINTERFACE_HH_

// include communication objects
#include <CommNavigationObjects/CommGridMap.hh>
#include <CommNavigationObjects/CommGridMapACE.hh>
#include <CommNavigationObjects/CommGridMapRequest.hh>
#include <CommNavigationObjects/CommGridMapRequestACE.hh>
#include <CommBasicObjects/CommMobileLaserScan.hh>
#include <CommBasicObjects/CommMobileLaserScanACE.hh>

#include <chrono>

// include component's main class
#include "SmartMapperGridMap.hh"

// forward declaration
class SmartMapperGridMap;

class SmartMapperGridMapPortFactoryInterface {
public:
	SmartMapperGridMapPortFactoryInterface() { };
	virtual ~SmartMapperGridMapPortFactoryInterface() { };

	virtual void initialize(SmartMapperGridMap *component, int argc, char* argv[]) = 0;
	virtual int onStartup() = 0;

	virtual Smart::IPushClientPattern<CommBasicObjects::CommMobileLaserScan> * createLaserServiceIn() = 0;
	
	virtual Smart::IPushServerPattern<CommNavigationObjects::CommGridMap> * createCurrMapOut(const std::string &serviceName) = 0;
	virtual Smart::IQueryServerPattern<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap,SmartACE::QueryId> * createCurrQueryServer(const std::string &serviceName) = 0;
	virtual Smart::IQueryServerPattern<CommNavigationObjects::CommGridMapRequest, CommNavigationObjects::CommGridMap,SmartACE::QueryId> * createLtmQueryServer(const std::string &serviceName) = 0;

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) = 0;
	virtual void destroy() = 0;
};

#endif /* SMARTMAPPERGRIDMAP_PORTFACTORYINTERFACE_HH_ */
