//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENTWEBOTS2DLIDAR_ACE_PORTFACTORY_HH_
#define COMPONENTWEBOTS2DLIDAR_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "ComponentWebots2DLidarImpl.hh"

// include the main component-definition class
#include "ComponentWebots2DLidarPortFactoryInterface.hh"

class ComponentWebots2DLidarAcePortFactory: public ComponentWebots2DLidarPortFactoryInterface
{
private:
	ComponentWebots2DLidarImpl *componentImpl;
public:
	ComponentWebots2DLidarAcePortFactory();
	virtual ~ComponentWebots2DLidarAcePortFactory();

	virtual void initialize(ComponentWebots2DLidar *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<CommBasicObjects::CommBaseState> * createBaseStateServiceIn() override;
	
	virtual Smart::IQueryServerPattern<CommBasicObjects::CommVoid, CommBasicObjects::CommMobileLaserScan> * createLaserQueryServiceAnsw(const std::string &serviceName) override;
	virtual Smart::IPushServerPattern<CommBasicObjects::CommMobileLaserScan> * createLaserServiceOut(const std::string &serviceName) override;
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* COMPONENTWEBOTS2DLIDAR_ACE_PORTFACTORY_HH_ */
